name: expensetracker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  logger: ^2.5.0
  in_app_update: ^4.2.3
  upgrader: ^11.3.1
  fluttertoast: ^8.2.12
  flutter_screenutil: ^5.9.3
  go_router: ^14.8.1
  flutter_bloc: ^9.1.0
  smooth_page_indicator: ^1.2.1
  equatable: ^2.0.7
  animated_bottom_navigation_bar: ^1.4.0
  fl_chart: ^0.70.2
  circular_menu: ^4.0.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
